function [fitresult, gof] = tankfill_fit(dQ, delta_p)
%  Auto-generated by MATLAB on 19-May-2021 01:35:27
%% Fit: 'tank_fill'.
[xData, yData] = prepareCurveData( dQ, delta_p );

% Set up fittype and options.
ft = fittype( 'eff_faraday_builtin.*dQ', 'independent', 'dQ', 'dependent', 'dp' );
opts = fitoptions( 'Method', 'nonlinearleastsquares' );
opts.Display = 'Off';
opts.StartPoint = 1;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure;
title("interptreter","latex")
plot(fitresult, xData, yData);
legend('$\Delta p$ vs. $\Delta Q$', "$\eta_F = $" + num2str(fitresult.eff_faraday_builtin), 'Location', 'best', 'Interpreter', 'latex' );
% Label axes
xlabel( '$\Delta Q ~[A\cdot s]$', 'Interpreter', 'latex' );
ylabel( '$\Delta p ~[Pa]$', 'Interpreter', 'latex' );
grid on


